<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#14233c">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <title>États des lieux</title>
  <link rel="manifest" href="./manifest.webmanifest">
  <link rel="apple-touch-icon" href="./apple-touch-icon.png">
  <link rel="icon" href="./favicon-32.png">
  <style>
    :root{--navy:#14233c;--navy2:#203554;--gold:#d8ad55;--ink:#172033;--muted:#68758a;--line:#dce2ea;--bg:#f3f5f8;--white:#fff;--green:#16815d;--red:#be3d4b;--amber:#a96513;--radius:18px;--shadow:0 10px 30px rgba(20,35,60,.08)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;padding-bottom:92px}button,input,select,textarea{font:inherit}button{cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}input,select,textarea{width:100%;border:1px solid var(--line);border-radius:12px;background:#fff;padding:12px 13px;color:var(--ink);outline:none;transition:.18s}input:focus,select:focus,textarea:focus{border-color:#7d8fa9;box-shadow:0 0 0 3px rgba(32,53,84,.1)}textarea{min-height:88px;resize:vertical}label{display:block;color:#455268;font-size:12px;font-weight:750}label>input,label>select,label>textarea{margin-top:6px}.hidden{display:none!important}.muted{color:var(--muted)}
    .topbar{position:sticky;top:0;z-index:30;height:68px;display:flex;align-items:center;gap:12px;padding:10px max(16px,calc((100vw - 1180px)/2));background:rgba(255,255,255,.94);backdrop-filter:blur(14px);border-bottom:1px solid var(--line)}.brand{display:flex;align-items:center;gap:11px;min-width:0}.brand img{width:43px;height:43px;border-radius:12px}.brand-copy strong{display:block;font-size:16px;letter-spacing:-.2px}.brand-copy span{display:block;color:var(--muted);font-size:11px}.top-actions{margin-left:auto;display:flex;gap:8px}.icon-btn,.btn{border:0;border-radius:12px;padding:11px 14px;font-weight:800}.icon-btn{width:42px;padding:0;background:#edf1f5;color:var(--navy)}.btn{background:var(--navy);color:#fff}.btn:hover{background:var(--navy2)}.btn.secondary{background:#edf1f5;color:var(--navy)}.btn.ghost{background:#fff;color:var(--navy);border:1px solid var(--line)}.btn.danger{background:#fff0f1;color:var(--red)}.btn.success{background:var(--green)}.btn.gold{background:var(--gold);color:#30250f}.btn.small{padding:8px 10px;font-size:12px}
    main{width:min(1180px,100%);margin:auto;padding:24px 16px}.view{display:none}.view.active{display:block}.hero{display:flex;justify-content:space-between;gap:18px;align-items:end;margin:8px 0 22px}.eyebrow{color:var(--gold);font-size:11px;font-weight:900;letter-spacing:1.4px;text-transform:uppercase}.hero h1{font-size:clamp(27px,4vw,40px);line-height:1.08;letter-spacing:-1.1px;margin:5px 0}.hero p{margin:0;color:var(--muted)}.hero-actions{display:flex;gap:8px;flex-wrap:wrap}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.stat,.card{background:#fff;border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow)}.stat{padding:16px}.stat span{display:block;color:var(--muted);font-size:11px;font-weight:750}.stat strong{display:block;font-size:27px;margin-top:3px}.toolbar{display:grid;grid-template-columns:minmax(220px,1fr) auto auto;gap:9px;margin-bottom:14px}.search{position:relative}.search input{padding-left:40px}.search:before{content:"⌕";position:absolute;left:14px;top:8px;font-size:22px;color:var(--muted)}.catalog{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px}.empty{grid-column:1/-1;text-align:center;padding:54px 24px}.empty .empty-icon{font-size:43px}.record{padding:17px;position:relative}.record-top{display:flex;justify-content:space-between;gap:8px}.record h3{margin:12px 0 4px;font-size:17px}.record .meta{color:var(--muted);font-size:12px;min-height:39px}.record .actions{display:flex;gap:7px;margin-top:15px;flex-wrap:wrap}.badge{display:inline-flex;align-items:center;gap:5px;border-radius:999px;padding:5px 9px;background:#edf1f5;color:#536078;font-size:10px;font-weight:850}.badge.done{background:#e7f5ef;color:var(--green)}.badge.sign{background:#fff4df;color:var(--amber)}
    .editor-head{display:flex;align-items:center;gap:12px;margin-bottom:14px}.editor-head-copy{min-width:0;flex:1}.editor-head h1{font-size:23px;margin:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.editor-head p{margin:2px 0 0;color:var(--muted);font-size:12px}.save-dot{display:flex;align-items:center;gap:7px;color:var(--muted);font-size:11px}.save-dot:before{content:"";width:8px;height:8px;border-radius:99px;background:var(--green)}.stepper{position:sticky;top:76px;z-index:20;display:grid;grid-template-columns:repeat(6,1fr);padding:7px;background:#fff;border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow);margin-bottom:14px}.step-btn{border:0;background:transparent;padding:10px 5px;border-radius:11px;color:var(--muted);font-size:11px;font-weight:800}.step-btn span{display:inline-grid;place-items:center;width:24px;height:24px;border-radius:99px;background:#edf1f5;margin-right:5px}.step-btn.active{background:var(--navy);color:#fff}.step-btn.active span{background:var(--gold);color:#30250f}.step-btn.complete{color:var(--green)}.panel{display:none}.panel.active{display:block}.card{padding:20px;margin-bottom:14px}.card-title{display:flex;align-items:start;justify-content:space-between;gap:12px;margin-bottom:16px}.card-title h2{font-size:18px;margin:0}.card-title p{font-size:12px;color:var(--muted);margin:3px 0 0}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:13px}.grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.section-note{padding:12px 14px;background:#f4f7fa;border-left:3px solid var(--gold);border-radius:9px;color:#526076;font-size:12px;margin:0 0 14px}.required:after{content:" *";color:var(--red)}
    .room-list{display:grid;gap:12px}.room{border:1px solid var(--line);border-radius:16px;background:#fff;overflow:hidden}.room.validated{border-color:#8bc9b2}.room-head{display:flex;align-items:center;gap:10px;padding:14px 15px;background:#f8fafc}.room-number{display:grid;place-items:center;width:31px;height:31px;border-radius:10px;background:var(--navy);color:#fff;font-size:12px;font-weight:900}.room-name{font-weight:850;flex:1}.room-summary{color:var(--muted);font-size:11px}.room-body{padding:14px}.quick-bar{display:flex;gap:7px;flex-wrap:wrap;margin-bottom:12px}.element-head,.element{display:grid;grid-template-columns:1.05fr .75fr 1.3fr 38px;gap:8px;align-items:center}.element-head{padding:0 3px 6px;color:var(--muted);font-size:10px;font-weight:850;text-transform:uppercase}.element{margin-bottom:8px}.element input,.element select{padding:10px;font-size:13px}.state-good{border-color:#8bc9b2!important;background:#f2fbf7!important}.state-bad{border-color:#e7a0a7!important;background:#fff5f5!important}.photos{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:12px}.photo{position:relative}.photo img{width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:11px}.photo input{padding:7px;font-size:11px}.photo button{position:absolute;top:5px;right:5px;width:27px;height:27px;padding:0;border:0;border-radius:99px;background:rgba(20,35,60,.85);color:white}.upload{display:flex;align-items:center;justify-content:center;min-height:105px;border:1.5px dashed #b8c2d0;border-radius:12px;background:#fafbfd;color:var(--navy);font-weight:800;cursor:pointer}.upload input{display:none}
    .meter-card{padding:14px;border:1px solid var(--line);border-radius:14px}.meter-card strong{font-size:13px}.meter-card .unit{position:relative}.meter-card .unit span{position:absolute;right:12px;bottom:11px;color:var(--muted);font-size:11px}.meter-card .unit input{padding-right:52px}.keys-table{display:grid;grid-template-columns:1fr 100px 38px;gap:8px;align-items:end;margin-bottom:8px}.signature-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.signature-box{border:1px solid var(--line);border-radius:15px;padding:14px}.signature-box canvas{width:100%;height:170px;border:1.5px dashed #aeb9c7;border-radius:12px;background:#fff;touch-action:none;margin:10px 0 7px}.legal{max-height:180px;overflow:auto;padding:13px;background:#f6f8fa;border-radius:11px;font-size:11px;color:#536078}.checkline{display:flex;align-items:flex-start;gap:9px;margin-top:12px;font-size:12px;font-weight:700}.checkline input{width:18px;height:18px;margin:0;flex:0 0 auto}.review-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:14px}.checklist{display:grid;gap:8px}.check{display:flex;align-items:center;gap:10px;padding:11px;border-radius:11px;background:#f5f7f9;font-size:12px}.check:before{content:"!";display:grid;place-items:center;width:22px;height:22px;border-radius:99px;background:#fff0df;color:var(--amber);font-weight:900}.check.ok:before{content:"✓";background:#e5f5ee;color:var(--green)}
    .bottom{position:fixed;left:0;right:0;bottom:0;z-index:35;background:rgba(255,255,255,.96);backdrop-filter:blur(14px);border-top:1px solid var(--line);padding:10px max(16px,calc((100vw - 1180px)/2)) calc(10px + env(safe-area-inset-bottom));display:flex;align-items:center;gap:9px}.bottom .spacer{flex:1}.mobile-label{display:inline}.modal{position:fixed;inset:0;z-index:80;display:none;align-items:center;justify-content:center;padding:16px;background:rgba(10,20,36,.7)}.modal.open{display:flex}.modal-card{width:min(680px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:22px;padding:22px;box-shadow:0 25px 80px rgba(0,0,0,.25)}.modal-head{display:flex;justify-content:space-between;align-items:start;gap:15px;margin-bottom:18px}.modal-head h2{margin:0}.room-picker{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.room-option{border:1px solid var(--line);background:#fff;color:var(--ink);border-radius:13px;padding:13px;text-align:left}.room-option:hover{border-color:var(--navy)}.room-option strong{display:block}.room-option small{color:var(--muted)}.toast{position:fixed;z-index:100;left:50%;bottom:90px;transform:translate(-50%,20px);opacity:0;background:var(--navy);color:#fff;border-radius:12px;padding:11px 16px;font-size:12px;font-weight:750;transition:.25s;pointer-events:none}.toast.show{opacity:1;transform:translate(-50%,0)}
    @media(max-width:800px){body{padding-bottom:84px}.topbar{height:62px;padding:8px 12px}.brand img{width:38px;height:38px}.brand-copy span{display:none}main{padding:16px 12px}.hero{align-items:start;flex-direction:column}.stats{grid-template-columns:repeat(2,1fr)}.catalog{grid-template-columns:1fr 1fr}.stepper{top:68px;overflow-x:auto;display:flex}.step-btn{min-width:112px}.grid.three{grid-template-columns:1fr 1fr}.photos{grid-template-columns:repeat(3,1fr)}.review-grid{grid-template-columns:1fr}}
    @media(max-width:560px){.top-actions .secondary{display:none}.hero h1{font-size:29px}.toolbar{grid-template-columns:1fr auto}.toolbar .import-label{display:none}.catalog{grid-template-columns:1fr}.grid,.grid.three,.signature-grid{grid-template-columns:1fr}.card{padding:15px}.element-head{display:none}.element{grid-template-columns:1fr 1fr 38px}.element [data-k="description"]{grid-column:1/3}.photos{grid-template-columns:repeat(2,1fr)}.room-head{align-items:flex-start;flex-wrap:wrap}.room-summary{width:100%;padding-left:41px}.bottom .btn{padding:11px}.mobile-label{display:none}.editor-head .btn{display:none}.room-picker{grid-template-columns:1fr}}
    @media print{body{background:#fff;padding:0;font-size:11px}.topbar,.stepper,.bottom,.no-print,.toast{display:none!important}main{width:100%;padding:0}.view{display:none!important}#printView{display:block!important}.print-page{page-break-after:always;padding:12mm 13mm}.print-page:last-child{page-break-after:auto}.print-brand{display:flex;align-items:center;border-bottom:2px solid var(--navy);padding-bottom:6mm;margin-bottom:6mm}.print-brand img{width:15mm;border-radius:4mm;margin-right:4mm}.print-brand h1{margin:0;font-size:20px}.print-brand p{margin:1mm 0 0;color:#666}.print-section{margin:5mm 0}.print-section h2{background:var(--navy);color:#fff;padding:2.5mm 3mm;font-size:12px;margin:0 0 2mm}.print-table{width:100%;border-collapse:collapse}.print-table th,.print-table td{border:1px solid #cbd1d8;padding:2mm;text-align:left;vertical-align:top}.print-table th{background:#f0f2f5}.print-photos{display:grid;grid-template-columns:repeat(3,1fr);gap:3mm}.print-photos img{width:100%;height:48mm;object-fit:cover}.print-signs{display:grid;grid-template-columns:1fr 1fr;gap:5mm}.print-sign{border:1px solid #bbb;min-height:38mm;padding:3mm}.print-sign img{width:100%;height:24mm;object-fit:contain}.page-footer{margin-top:5mm;border-top:1px solid #bbb;padding-top:2mm;color:#777;font-size:9px}}
    /* Finition produit : mouvement, tactilité et accessibilité */
    :focus-visible{outline:3px solid rgba(216,173,85,.55);outline-offset:3px}
    .btn,.icon-btn,.step-btn,.room-option,.record{transition:transform .18s cubic-bezier(.2,.8,.2,1),box-shadow .18s ease,background-color .18s ease,border-color .18s ease}
    .btn:hover,.room-option:hover{transform:translateY(-1px);box-shadow:0 8px 18px rgba(20,35,60,.12)}
    .btn:active,.icon-btn:active,.step-btn:active,.room-option:active{transform:scale(.97)}
    .record:hover{transform:translateY(-3px);box-shadow:0 16px 36px rgba(20,35,60,.12);border-color:#c7d0dc}
    .view.active{animation:viewIn .32s cubic-bezier(.2,.8,.2,1)}
    .panel.active{animation:panelIn .3s cubic-bezier(.2,.8,.2,1)}
    .room{animation:cardIn .3s cubic-bezier(.2,.8,.2,1) both}
    .room:nth-child(2){animation-delay:.035s}.room:nth-child(3){animation-delay:.07s}.room:nth-child(4){animation-delay:.105s}
    .modal.open .modal-card{animation:modalIn .28s cubic-bezier(.2,.9,.2,1)}
    .save-dot:before{animation:savedPulse 2.4s infinite}
    .upload{transition:border-color .18s,background-color .18s,transform .18s}.upload:hover{border-color:var(--gold);background:#fffaf0;transform:translateY(-1px)}
    .room.validated{box-shadow:0 0 0 3px rgba(22,129,93,.07)}
    .step-btn.complete span{background:#e5f5ee;color:var(--green)}
    .element select{transition:background-color .2s,border-color .2s}
    .ripple{position:fixed;width:10px;height:10px;border-radius:50%;background:rgba(216,173,85,.38);transform:translate(-50%,-50%) scale(0);animation:ripple .5s ease-out;pointer-events:none;z-index:200}
    @keyframes viewIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
    @keyframes panelIn{from{opacity:0;transform:translateX(10px)}to{opacity:1;transform:none}}
    @keyframes cardIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
    @keyframes modalIn{from{opacity:0;transform:translateY(14px) scale(.975)}to{opacity:1;transform:none}}
    @keyframes savedPulse{0%,75%,100%{box-shadow:0 0 0 0 rgba(22,129,93,.28)}85%{box-shadow:0 0 0 7px rgba(22,129,93,0)}}
    @keyframes ripple{to{transform:translate(-50%,-50%) scale(12);opacity:0}}
    @media(max-width:560px){button,.btn,.icon-btn,.step-btn{min-height:44px}.record:hover{transform:none}.bottom{box-shadow:0 -12px 30px rgba(20,35,60,.08)}.topbar{box-shadow:0 4px 18px rgba(20,35,60,.05)}}
    @media(prefers-reduced-motion:reduce){*,*:before,*:after{scroll-behavior:auto!important;animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important}}
    /* V2 mobile-first : comparaison lisible et PDF premium */
    .source-list{display:grid;gap:9px}.source-card{display:flex;flex-direction:column;gap:3px;width:100%;padding:14px;border:1px solid var(--line);border-radius:14px;background:#fff;text-align:left;color:var(--ink)}.source-card span{font-size:11px;color:var(--muted)}
    .comparison-banner{display:flex;justify-content:space-between;gap:8px;padding:10px 12px;margin-bottom:10px;border-radius:11px;background:#edf3fb;color:var(--navy);font-size:11px}.comparison-banner span{color:#52647d}
    .entry-memory{display:flex;align-items:center;gap:6px;margin-top:5px;padding:7px 8px;border-radius:9px;background:#f1f4f8;font-size:10px}.entry-memory span{color:var(--muted);text-transform:uppercase;font-weight:850}.entry-memory small{display:block;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.change-state{display:grid;place-items:center;min-height:38px;border-radius:10px;background:#f1f4f8;color:var(--muted);font-size:9px;font-weight:900}.change-state.changed{background:#fff0df;color:#9a5c0a}.room-validate{display:flex;justify-content:flex-end;margin-top:13px}
    @media(max-width:560px){body{font-size:14px}.brand-copy strong{font-size:15px}.hero{margin-top:2px}.hero p{font-size:13px}.stats{gap:8px}.stat{padding:13px}.stat strong{font-size:23px}.card{border-radius:16px}.editor-head{position:relative}.editor-head h1{font-size:19px}.stepper{margin-left:-12px;margin-right:-12px;border-radius:0;border-left:0;border-right:0;box-shadow:0 6px 16px rgba(20,35,60,.06)}.step-btn{min-width:98px;font-size:10px}.step-btn span{display:block;margin:0 auto 4px}.room-head{padding:12px}.room-body{padding:11px}.quick-bar{display:grid;grid-template-columns:1fr 1fr}.quick-bar .btn{width:100%}.compare-element{grid-template-columns:1fr 42px!important;padding:11px 0;border-bottom:1px solid #edf0f4}.compare-element .element-name{grid-column:1/-1}.compare-element select{grid-column:1/2}.compare-element [data-k="description"]{grid-column:1/-1!important;grid-row:auto}.compare-element .change-state{grid-column:2;grid-row:2}.entry-memory{display:grid;grid-template-columns:auto 1fr}.entry-memory small{grid-column:1/-1}.photos{grid-template-columns:1fr 1fr}.bottom{gap:6px;padding-left:9px;padding-right:9px}.bottom .btn{padding:10px 9px;font-size:12px}#manualSaveBtn{background:#e8f4ef;color:var(--green)}#printBtn{padding-left:12px;padding-right:12px}.signature-box canvas{height:150px}.modal{align-items:flex-end;padding:0}.modal-card{border-radius:24px 24px 0 0;max-height:92vh;padding:20px 16px calc(20px + env(safe-area-inset-bottom));animation:sheetIn .28s cubic-bezier(.2,.9,.2,1)!important}@keyframes sheetIn{from{transform:translateY(100%)}to{transform:none}}}
    @media print{.premium-pdf{color:#172033}.pdf-cover{position:relative;min-height:85mm;padding:13mm;background:linear-gradient(135deg,#14233c,#223b61);color:#fff;border-radius:0 0 8mm 8mm;display:grid;grid-template-columns:24mm 1fr;gap:8mm}.pdf-cover>img{width:24mm;height:24mm}.pdf-cover-copy>span{color:#e8c675;font-size:9px;letter-spacing:1.5px;font-weight:800}.pdf-cover-copy h1{font-size:27px;line-height:1.05;margin:3mm 0 5mm}.pdf-cover-copy p{font-size:13px;line-height:1.5}.pdf-ref{position:absolute;right:13mm;bottom:10mm;display:flex;flex-direction:column;text-align:right}.pdf-ref span{font-size:9px;opacity:.75}.pdf-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:3mm;margin:7mm 0}.pdf-summary>div{padding:4mm;background:#f3f5f8;border-radius:3mm}.pdf-summary span,.pdf-summary small{display:block;color:#68758a;font-size:9px}.pdf-summary b{display:block;margin:1mm 0;font-size:11px}.pdf-link{padding:3mm 4mm;background:#fff7e6;border-left:1.5mm solid #d8ad55;margin-bottom:5mm}.pdf-section{break-inside:auto;margin:6mm 0}.pdf-section>h2{font-size:14px;color:#14233c;border-bottom:1px solid #d8ad55;padding-bottom:2mm}.pdf-room-title{display:flex;align-items:center;gap:3mm;margin-bottom:3mm;break-after:avoid}.pdf-room-title>b{display:grid;place-items:center;width:11mm;height:11mm;border-radius:3mm;background:#14233c;color:#fff;font-size:13px}.pdf-room-title h2{margin:0;font-size:14px}.pdf-room-title span{color:#68758a;font-size:9px}.premium-table{break-inside:auto}.premium-table thead{display:table-header-group}.premium-table tr{break-inside:avoid}.premium-table td small{display:block;color:#68758a;margin-top:1mm}.premium-table .pdf-alert td{background:#fff5f3}.print-photos{margin-top:4mm}.print-photos figure{margin:0;break-inside:avoid}.print-photos figcaption{font-size:8px;color:#68758a}.pdf-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:3mm}.pdf-kpis div{padding:4mm;text-align:center;background:#f3f5f8;border-radius:3mm}.pdf-kpis b{display:block;font-size:22px;color:#14233c}.pdf-kpis span{font-size:9px;color:#68758a}.pdf-notes{display:grid;grid-template-columns:1fr 1fr;gap:4mm}.pdf-notes p{padding:4mm;background:#f6f7f9;min-height:20mm}.pdf-signature-page{break-inside:avoid}.print-sign{display:flex;flex-direction:column}.print-sign span{font-size:9px;color:#68758a}.print-sign img{margin-top:auto}}
    /* Identité volontairement neutre : aucun logo ni marque */
    .brand{padding-left:2px}.brand-copy strong{font-size:17px;letter-spacing:-.25px}.pdf-cover>img{display:none!important}
    @media print{.pdf-cover{grid-template-columns:1fr!important}.pdf-cover-copy{max-width:125mm}.pdf-cover-copy>span{color:#d8ad55}.premium-pdf .page-footer{text-align:center}}
    /* Mobile V3 — interface terrain, calme et hiérarchisée */
    .mobile-step-status{display:none}
    @media(max-width:560px){
      :root{--radius:16px;--shadow:none}
      html{background:#f7f8fa}body{background:#f7f8fa;padding-bottom:82px;color:#111827}
      .topbar{height:56px;padding:8px 16px;background:rgba(247,248,250,.96);border-bottom:0;box-shadow:none}
      .brand-copy strong{font-size:16px;font-weight:800}.brand-copy span{display:none}.top-actions{gap:4px}.top-actions .btn{min-width:40px;min-height:40px;padding:0 10px;background:#fff;border:1px solid #e4e8ee;font-size:0}.top-actions #backupBtn:after{content:"↥";font-size:19px}.top-actions #installBtn:after{content:"↓";font-size:17px}
      main{padding:12px 14px 24px;max-width:520px}
      .view.active,.panel.active,.room{animation:mobileFade .16s ease-out both}.room:nth-child(n){animation-delay:0s}.ripple{display:none!important}
      @keyframes mobileFade{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:none}}

      /* Accueil utile, sans écran marketing */
      .hero{display:block;margin:4px 0 18px}.hero .eyebrow{font-size:10px;letter-spacing:1.3px;color:#7b8798}.hero h1{font-size:28px;line-height:1.08;letter-spacing:-.8px;margin:5px 0 7px}.hero h1 br{display:none}.hero p{font-size:13px;line-height:1.45;max-width:330px}.hero-actions{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:17px}.hero-actions .btn{min-height:58px;padding:10px 12px;text-align:left;line-height:1.2;border-radius:14px;box-shadow:none}.hero-actions .gold{background:#fff;color:#172033;border:1px solid #dde3eb}.hero-actions #newExit{background:#172b49}
      .stats{display:flex;gap:7px;overflow-x:auto;margin:0 -14px 15px;padding:0 14px 2px;scrollbar-width:none}.stats::-webkit-scrollbar{display:none}.stat{flex:0 0 auto;display:flex;align-items:center;gap:7px;padding:8px 11px;border-radius:999px;background:#fff;border-color:#e5e9ef}.stat span{font-size:10px;white-space:nowrap}.stat strong{font-size:13px;margin:0;order:-1}
      .toolbar{display:grid;grid-template-columns:1fr 44px;gap:8px;margin-bottom:11px}.search input{height:46px;border:0;background:#fff;box-shadow:0 1px 0 #e4e8ee;padding-left:39px}.toolbar select{width:44px;height:46px;padding:0;border:0;background:#fff;color:transparent;background-image:none}.toolbar select:after{content:""}.toolbar .import-label{display:none}
      .catalog{gap:8px}.record{padding:15px;border:0;border-radius:15px;box-shadow:0 1px 0 #e2e6ec}.record:hover{transform:none}.record h3{margin:10px 0 3px;font-size:16px}.record .meta{min-height:auto;line-height:1.45}.record .actions{display:grid;grid-template-columns:1fr auto auto;margin-top:13px}.record .actions .btn{min-height:40px}.record-top{align-items:center}.badge{padding:4px 8px}

      /* Éditeur : contexte compact et progression lisible */
      .editor-head{display:grid;grid-template-columns:42px 1fr auto;gap:9px;margin:0 0 10px}.editor-head .icon-btn{width:42px;background:#fff;border:1px solid #e1e6ed}.editor-head-copy{align-self:center}.editor-head h1{font-size:16px;line-height:1.2}.editor-head p{font-size:10px;max-width:230px}.editor-head #saveState{font-size:0}.editor-head #saveState:before{width:9px;height:9px;animation:none}.editor-head #saveState:after{content:"Sauvé";font-size:10px;color:#64748b}.editor-head>.btn{display:none}
      .stepper{position:sticky;top:56px;display:block;margin:0 -14px 12px;padding:10px 14px 11px;border:0;border-radius:0;background:rgba(247,248,250,.97);box-shadow:0 1px 0 #e4e8ee;overflow:visible}.stepper>.step-btn{display:none}.mobile-step-status{display:grid;grid-template-columns:1fr auto;align-items:center;gap:3px 12px}.mobile-step-status div:first-child{display:flex;align-items:baseline;gap:8px}.mobile-step-status span{font-size:9px;color:#778397;text-transform:uppercase;font-weight:800;letter-spacing:.5px}.mobile-step-status strong{font-size:13px}.mobile-step-status em{font-style:normal;font-size:10px;font-weight:800;color:#64748b}.mobile-progress{grid-column:1/-1;height:3px;background:#e3e8ef;border-radius:9px;overflow:hidden}.mobile-progress i{display:block;height:100%;background:#1d3557;border-radius:9px;transition:width .18s ease}
      .panel>.card,.review-grid .card{padding:16px;border:0;border-radius:16px;box-shadow:0 1px 0 #e2e6ec;margin-bottom:10px}.card-title{margin-bottom:14px}.card-title h2{font-size:17px;letter-spacing:-.2px}.card-title p{font-size:11px;line-height:1.45}.grid,.grid.three{gap:11px}.grid label,.grid.three label{grid-column:1/-1!important}label{font-size:11px;color:#526073}input,select,textarea{min-height:46px;border-color:#dce2ea;border-radius:11px;padding:11px 12px;background:#fbfcfd}textarea{min-height:104px}.section-note{font-size:11px;line-height:1.45;border-left:0;border-radius:12px;background:#eef3f8;padding:11px 12px}

      /* Inspection : une pièce à la fois, un élément à la fois */
      .room-list{gap:9px}.room{border:0;border-radius:16px;box-shadow:0 1px 0 #dde3ea;overflow:hidden}.room.validated{box-shadow:inset 0 0 0 1px #9bcdb9}.room-head{display:grid;grid-template-columns:34px 1fr 42px;gap:0 9px;padding:13px;background:#fff}.room-number{grid-row:1/3;width:34px;height:34px;border-radius:11px}.room-name{align-self:end;font-size:14px}.room-summary{width:auto;padding:0;align-self:start;font-size:9px}.room-head .icon-btn{grid-column:3;grid-row:1/3;width:40px;background:#f1f4f7}.room-body{padding:12px;background:#fafbfc;border-top:1px solid #edf0f3}.quick-bar{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-bottom:10px}.quick-bar .btn{min-height:40px;padding:8px;font-size:10px}.comparison-banner{display:grid;gap:2px;padding:10px;margin-bottom:8px}.element-head{display:none}.compare-element,.element{display:grid;grid-template-columns:1fr 38px!important;gap:7px;padding:12px 0;margin:0;border-bottom:1px solid #e5e9ee}.compare-element:last-of-type,.element:last-of-type{border-bottom:0}.element-name{grid-column:1/-1}.element-name>input,[data-element-name]{font-weight:750;background:#fff}.entry-memory{margin-top:6px;padding:8px;background:#eef2f6}.compare-element select,.element select{grid-column:1/2;grid-row:auto;min-height:44px}.compare-element [data-k="description"],.element [data-k="description"]{grid-column:1/-1!important;grid-row:auto}.change-state,.element>.icon-btn{grid-column:2;grid-row:2;width:38px;min-height:44px}.element>.icon-btn{background:#f2f4f7;color:#7b8798}.photos{grid-template-columns:1fr 1fr;gap:8px}.photo img{border-radius:10px}.upload{min-height:118px;background:#fff}.room-validate .btn{width:100%;min-height:46px}.room-actions{display:grid;grid-template-columns:1fr 1fr}
      .meter-card{padding:12px;background:#fbfcfd}.keys-table{grid-template-columns:1fr 82px 40px}.signature-grid{gap:10px}.signature-box{padding:12px}.signature-box canvas{height:150px;margin-top:8px}.review-grid{display:block}

      /* Barre au pouce : une seule action dominante */
      .bottom{height:72px;display:grid;grid-template-columns:44px 96px 1fr;gap:7px;padding:9px 12px calc(9px + env(safe-area-inset-bottom));background:rgba(255,255,255,.97);box-shadow:0 -1px 0 #e0e5eb}.bottom .spacer{display:none}.bottom .btn{min-height:46px;border-radius:12px;font-size:12px;padding:9px}.bottom #prevBtn{grid-column:1;font-size:0}.bottom #prevBtn:before{content:"←";font-size:18px}.bottom #manualSaveBtn{grid-column:2;background:#eef2f6;color:#243650}.bottom #printBtn{display:none}.bottom #printBtn.mobile-final-action{display:block;grid-column:2}.bottom #printBtn.mobile-final-action+#nextBtn{grid-column:3}.bottom #nextBtn{grid-column:3;background:#172b49;font-size:13px}.bottom #nextBtn span{margin-left:4px}
      .modal-card{box-shadow:0 -16px 50px rgba(13,25,42,.18)}.modal-head h2{font-size:20px}.source-card{min-height:64px}
    }
    /* Workflow V4 — préparation guidée et progression discrète */
    .journey-copy{display:flex;align-items:baseline;gap:8px}.journey-copy span{font-size:10px;color:#7b8798;font-weight:800}.journey-copy strong{font-size:13px}.journey-dots{display:flex;align-items:center;gap:6px}.journey-dots i{display:block;width:6px;height:6px;border-radius:50%;background:#d5dbe3}.journey-dots i.done{background:#7e9b8e}.journey-dots i.current{width:18px;border-radius:99px;background:#1d3557}.identity-group{padding:15px 0;border-top:1px solid #e8ecf1}.identity-group:first-of-type{border-top:0;padding-top:0}.identity-group h3{font-size:13px;margin:0 0 11px}.identity-group h3 span{color:#8a94a4;font-size:10px;font-weight:500}.setup-top{display:flex;align-items:center;gap:12px;padding-bottom:16px;border-bottom:1px solid #e8ecf1}.setup-top>div{min-width:0}.setup-top span,.source-kicker{display:block;color:#7b8798;font-size:9px;font-weight:850;letter-spacing:.7px;text-transform:uppercase}.setup-top h2{margin:2px 0 0;font-size:21px}.setup-body{padding:18px 0}.setup-question{font-size:17px;font-weight:800;letter-spacing:-.2px;margin:0 0 15px}.setup-help{font-size:11px;margin:-9px 0 14px}.setup-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding-top:13px;border-top:1px solid #e8ecf1}.wizard-room-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.wizard-room{display:flex;flex-direction:column;align-items:flex-start;justify-content:center;min-height:65px;padding:11px;border:1px solid #dfe4eb;border-radius:13px;background:#fff;color:#1b2739;text-align:left}.wizard-room span{font-size:12px;font-weight:800}.wizard-room small{font-size:9px;color:#7d899a;margin-top:2px}.wizard-room.selected{border-color:#1d3557;background:#eef3f8;box-shadow:inset 0 0 0 1px #1d3557}.pdf-import{display:block;padding:15px;border:1.5px dashed #aeb9c7;border-radius:14px;background:#f8fafc;cursor:pointer}.pdf-import input{display:none}.pdf-import strong,.pdf-import span{display:block}.pdf-import strong{font-size:13px;color:#1d3557}.pdf-import span{font-size:10px;color:#778397;margin-top:3px;line-height:1.4}
    @media(max-width:560px){.hero>div:first-child{display:none}.hero{margin:0 0 12px}.hero-actions{margin-top:0}.hero-actions .btn{min-width:0;min-height:64px;font-size:12px;padding:10px}.hero-actions #newEntry,.hero-actions #newExit{display:flex;align-items:center;justify-content:center;text-align:center}.mobile-step-status{grid-template-columns:1fr auto}.mobile-step-status .mobile-progress{display:none}.journey-dots{justify-content:flex-end}.setup-card{padding-top:14px}.setup-body .grid{display:grid}.setup-actions .btn{min-height:48px}.wizard-room-grid{gap:7px}.wizard-room{min-height:62px;padding:10px}.identity-group{padding:14px 0}.source-modal .modal-head{margin-bottom:14px}.source-modal .source-list{max-height:36vh;overflow:auto}.pdf-import{margin-top:10px}}
  </style>
</head>
<body>
  <header class="topbar">
    <div class="brand"><div class="brand-copy"><strong>États des lieux</strong><span>Gestion professionnelle · données locales</span></div></div>
    <div class="top-actions"><button id="backupBtn" class="btn secondary">Sauvegarder les données</button><button id="installBtn" class="btn ghost hidden">Installer</button></div>
  </header>
  <main>
    <section id="homeView" class="view active">
      <div class="hero"><div><div class="eyebrow">Votre journée terrain</div><h1>Des états des lieux<br>nets, rapides, incontestables.</h1><p>Tout reste enregistré sur cet appareil, même sans réseau.</p></div><div class="hero-actions"><button id="newEntry" class="btn gold">＋ État des lieux d’entrée</button><button id="newExit" class="btn">＋ État des lieux de sortie</button></div></div>
      <div class="stats"><div class="stat"><span>Dossiers</span><strong id="statAll">0</strong></div><div class="stat"><span>À terminer</span><strong id="statDraft">0</strong></div><div class="stat"><span>À signer</span><strong id="statSign">0</strong></div><div class="stat"><span>Terminés</span><strong id="statDone">0</strong></div></div>
      <div class="toolbar"><div class="search"><input id="search" placeholder="Adresse, locataire, référence…"></div><select id="statusFilter"><option value="">Tous les statuts</option><option>Brouillon</option><option>À signer</option><option>Terminé</option></select><label class="btn ghost import-label">Importer<input id="importFile" class="hidden" type="file" accept="application/json"></label></div>
      <div id="catalog" class="catalog"></div>
    </section>
    <section id="editorView" class="view">
      <div class="editor-head"><button id="backBtn" class="icon-btn" aria-label="Retour">←</button><div class="editor-head-copy"><h1 id="editorTitle">Nouvel état des lieux</h1><p id="editorSub"></p></div><div id="saveState" class="save-dot">Enregistré</div><button id="duplicateBtn" class="btn ghost">Dupliquer en sortie</button></div>
      <nav id="stepper" class="stepper"></nav>
      <div id="panels"></div>
    </section>
    <section id="printView" class="view"></section>
  </main>
  <div id="bottom" class="bottom hidden"><button id="prevBtn" class="btn secondary">← <span class="mobile-label">Précédent</span></button><div class="spacer"></div><button id="manualSaveBtn" class="btn secondary">Enregistrer</button><button id="printBtn" class="btn ghost">PDF</button><button id="nextBtn" class="btn"><span class="mobile-label">Suivant</span> →</button></div>
  <div id="roomModal" class="modal"><div class="modal-card"><div class="modal-head"><div><div class="eyebrow">Configuration</div><h2>Ajouter une pièce</h2></div><button class="icon-btn" data-close="roomModal">×</button></div><div id="roomPicker" class="room-picker"></div><div class="grid" style="margin-top:12px"><label>Nom personnalisé<input id="customRoom" placeholder="Ex. Chambre enfant"></label><button id="addCustomRoom" class="btn" style="align-self:end">Ajouter</button></div></div></div>
  <div id="confirmModal" class="modal"><div class="modal-card" style="max-width:440px"><div class="modal-head"><h2 id="confirmTitle">Confirmer</h2><button class="icon-btn" data-close="confirmModal">×</button></div><p id="confirmText" class="muted"></p><div style="display:flex;justify-content:flex-end;gap:8px"><button class="btn secondary" data-close="confirmModal">Annuler</button><button id="confirmYes" class="btn danger">Confirmer</button></div></div></div>
  <div id="toast" class="toast"></div>
  <script>
  "use strict";
  const DB_KEY="constat-edl-v1",STEPS=["Dossier","Parties","Relevés","Pièces","Observations","Signatures"];
  const CONDITIONS=["Non vérifié","Neuf","Très bon état","Bon état","État d’usage","Passable","Mauvais état","À remplacer","Non concerné"];
  const ROOMS={
    "Entrée / dégagement":["Porte d’entrée","Serrure / poignée","Sonnette / interphone","Murs","Sol","Plafond","Éclairage / interrupteurs","Prises électriques"],
    "Séjour":["Porte","Murs","Sol","Plafond","Fenêtres / vitrages","Volets / stores","Radiateurs","Éclairage / interrupteurs","Prises électriques"],
    "Cuisine":["Porte","Murs","Sol","Plafond","Fenêtres / volets","Éclairage / interrupteurs","Prises électriques","Évier","Robinetterie","Plan de travail","Placards","Tiroirs","Plaques de cuisson","Four","Hotte","Réfrigérateur","Lave-vaisselle","VMC"],
    "Chambre":["Porte","Serrure / poignée","Murs","Sol","Plafond","Fenêtres / vitrages","Volets / stores","Radiateur","Éclairage / interrupteurs","Prises électriques","Placard"],
    "Salle de bains":["Porte","Murs","Sol","Plafond","Ventilation","Éclairage / interrupteurs","Prises électriques","Lavabo","Robinetterie","Baignoire","Pare-baignoire","WC","VMC"],
    "Salle d’eau":["Porte","Murs","Sol","Plafond","Ventilation","Éclairage / interrupteurs","Prises électriques","Lavabo","Robinetterie","Douche","Pare-douche","WC","VMC"],
    "WC":["Porte","Murs","Sol","Plafond","Éclairage","Lave-mains","Robinetterie","WC","Ventilation"],
    "Balcon / terrasse":["Sol","Murs / garde-corps","Éclairage","Prise électrique","Robinet extérieur","Évacuation d’eau"],
    "Bureau":["Porte","Murs","Sol","Plafond","Fenêtres / vitrages","Radiateur","Éclairage","Prises électriques"],
    "Dressing":["Porte","Murs","Sol","Plafond","Éclairage","Placards / étagères"],
    "Buanderie":["Porte","Murs","Sol","Plafond","Éclairage","Prises électriques","Arrivée d’eau","Évacuation d’eau","VMC"],
    "Cave":["Porte","Serrure","Murs","Sol","Plafond","Éclairage","Ventilation"],
    "Parking / garage":["Accès","Porte / portail","Télécommande","Sol","Murs","Plafond","Éclairage","Prise électrique"],
    "Autre":["Murs","Sol","Plafond","Éclairage","Prises électriques"]
  };
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],uid=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const localNow=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
  let records=[],current=null,step=0,saveTimer,confirmAction=null,deferredInstall=null;
  function emptyRecord(type="Entrée"){return{id:uid(),type,date:localNow(),address:"",postalCode:"",city:"",lot:"",floor:"",nature:"Appartement",furnished:"Non",reference:"EDL-"+new Date().getFullYear()+"-"+Math.random().toString(36).slice(2,7).toUpperCase(),landlord:"",landlordAddress:"",agent:"",tenant:"",tenant2:"",phone:"",email:"",meters:{electricity:"",electricityId:"",gas:"",gasId:"",coldWater:"",hotWater:""},keys:[{id:uid(),name:"Clés porte d’entrée",count:2}],rooms:[],observations:"",reserves:"",smokeDetector:"Non vérifié",cleanliness:"Non vérifié",heating:"Non vérifié",signTenantName:"",signLandlordName:"",signTenant:"",signLandlord:"",accepted:false,status:"Brouillon",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}}
  function makeRoom(name){const base=ROOMS[name]?name:"Autre";return{id:uid(),name,validated:false,photos:[],elements:ROOMS[base].map(n=>({id:uid(),name:n,condition:"Non vérifié",entryCondition:"Non vérifié",description:""}))}}
  function load(){try{records=JSON.parse(localStorage.getItem(DB_KEY)||"[]");if(!Array.isArray(records))records=[]}catch{records=[]}}
  function persist(){localStorage.setItem(DB_KEY,JSON.stringify(records))}
  function upsert(){if(!current)return;current.updatedAt=new Date().toISOString();const i=records.findIndex(r=>r.id===current.id);if(i<0)records.push(current);else records[i]=current;persist();setSave("Enregistré")}
  function schedule(){setSave("Enregistrement…",true);clearTimeout(saveTimer);saveTimer=setTimeout(upsert,350)}
  function setSave(text,busy=false){$("#saveState").textContent=text;$("#saveState").style.opacity=busy?.65:1}
  function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2300)}
  function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$("#bottom").classList.toggle("hidden",id!=="editorView")}
  function completion(r){let total=0;total+=r.address&&r.city&&r.date?15:0;total+=r.landlord&&r.tenant?15:0;total+=Object.values(r.meters).some(Boolean)&&r.keys.length?10:0;total+=r.rooms.length?Math.round(40*r.rooms.filter(x=>x.validated).length/r.rooms.length):0;total+=r.observations||r.reserves?5:0;total+=r.signTenant&&r.signLandlord&&r.accepted?15:0;return Math.min(100,total)}
  function deriveStatus(r){const p=completion(r);return p===100?"Terminé":(r.rooms.length&&r.rooms.every(x=>x.validated))?"À signer":"Brouillon"}
  function renderHome(){records.forEach(r=>r.status=deriveStatus(r));persist();const q=$("#search").value.trim().toLowerCase(),status=$("#statusFilter").value;const list=records.slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).filter(r=>(!status||r.status===status)&&`${r.address} ${r.city} ${r.tenant} ${r.reference} ${r.type}`.toLowerCase().includes(q));$("#statAll").textContent=records.length;$("#statDraft").textContent=records.filter(r=>r.status==="Brouillon").length;$("#statSign").textContent=records.filter(r=>r.status==="À signer").length;$("#statDone").textContent=records.filter(r=>r.status==="Terminé").length;$("#catalog").innerHTML=list.length?list.map(r=>`<article class="card record"><div class="record-top"><span class="badge ${r.status==='Terminé'?'done':r.status==='À signer'?'sign':''}">${r.status}</span><span class="muted" style="font-size:11px">${completion(r)} %</span></div><h3>${esc(r.address||"Adresse à renseigner")}</h3><div class="meta">${esc([r.postalCode,r.city].filter(Boolean).join(" ")||"Localité non renseignée")}<br>${esc(r.type)} · ${esc(r.tenant||"Locataire à renseigner")}</div><div class="actions"><button class="btn small" data-open="${r.id}">Ouvrir</button><button class="btn ghost small" data-copy="${r.id}">Copier</button><button class="btn danger small" data-delete="${r.id}">Supprimer</button></div></article>`).join(""):`<div class="card empty"><div class="empty-icon">⌂</div><h2>${records.length?"Aucun résultat":"Votre premier dossier commence ici"}</h2><p class="muted">Créez un état des lieux d’entrée ou de sortie. Il sera sauvegardé automatiquement.</p></div>`;$$('[data-open]').forEach(b=>b.onclick=()=>openRecord(b.dataset.open));$$('[data-copy]').forEach(b=>b.onclick=()=>duplicate(b.dataset.copy,false));$$('[data-delete]').forEach(b=>b.onclick=()=>askConfirm("Supprimer ce dossier ?","Cette action est définitive sur cet appareil.",()=>{records=records.filter(r=>r.id!==b.dataset.delete);persist();renderHome();toast("Dossier supprimé")}))}
  function newRecord(type){current=emptyRecord(type);["Entrée / dégagement","Séjour","Cuisine","Salle d’eau","WC"].forEach(n=>current.rooms.push(makeRoom(n)));step=0;upsert();renderEditor();showView("editorView")}
  function openRecord(id){current=records.find(r=>r.id===id);step=0;renderEditor();showView("editorView")}
  function duplicate(id,toExit=true){const src=records.find(r=>r.id===id),r=structuredClone(src);r.id=uid();r.reference="EDL-"+new Date().getFullYear()+"-"+Math.random().toString(36).slice(2,7).toUpperCase();r.type=toExit?"Sortie":src.type;r.date=localNow();r.signTenant=r.signLandlord="";r.accepted=false;r.status="Brouillon";r.createdAt=r.updatedAt=new Date().toISOString();r.rooms.forEach(room=>{room.id=uid();room.validated=false;room.photos=[];room.elements.forEach(e=>{e.id=uid();e.entryCondition=e.condition;e.condition="Non vérifié"})});records.push(r);persist();if(toExit){current=r;renderEditor();showView("editorView");toast("Dossier de sortie créé")}else{renderHome();toast("Copie créée")}}
  function renderEditor(){$("#editorTitle").textContent=`État des lieux d’${current.type.toLowerCase()}`;$("#editorSub").textContent=`${current.reference} · ${current.address||"Nouvelle adresse"} · ${completion(current)} %`;$("#duplicateBtn").classList.toggle("hidden",current.type==="Sortie");$("#stepper").innerHTML=STEPS.map((s,i)=>`<button class="step-btn ${i===step?'active':''} ${stepComplete(i)?'complete':''}" data-step="${i}"><span>${stepComplete(i)?'✓':i+1}</span>${s}</button>`).join("");$("#panels").innerHTML=STEPS.map((_,i)=>`<section class="panel ${i===step?'active':''}" data-panel="${i}">${panelHTML(i)}</section>`).join("");$("#prevBtn").disabled=step===0;$("#nextBtn").innerHTML=step===5?"Finaliser ✓":"<span class='mobile-label'>Suivant</span> →";bindEditor();window.scrollTo({top:0,behavior:"smooth"})}
  function stepComplete(i){if(!current)return false;return [!!(current.address&&current.city&&current.date),!!(current.landlord&&current.tenant),Object.values(current.meters).some(Boolean)&&current.keys.length>0,current.rooms.length>0&&current.rooms.every(r=>r.validated),!!(current.observations||current.reserves),!!(current.signTenant&&current.signLandlord&&current.accepted)][i]}
  function panelHTML(i){if(i===0)return `<div class="card"><div class="card-title"><div><h2>Le dossier</h2><p>Identification précise du bien et du constat.</p></div><span class="badge">${esc(current.reference)}</span></div><div class="grid three"><label class="required">Type<select data-field="type"><option ${current.type==='Entrée'?'selected':''}>Entrée</option><option ${current.type==='Sortie'?'selected':''}>Sortie</option></select></label><label class="required">Date et heure<input type="datetime-local" data-field="date" value="${esc(current.date)}"></label><label>Référence<input data-field="reference" value="${esc(current.reference)}"></label><label class="required" style="grid-column:span 2">Adresse complète<input data-field="address" value="${esc(current.address)}" placeholder="12 rue des Lilas"></label><label>Lot / appartement<input data-field="lot" value="${esc(current.lot)}" placeholder="Lot 12"></label><label class="required">Code postal<input inputmode="numeric" data-field="postalCode" value="${esc(current.postalCode)}"></label><label class="required">Ville<input data-field="city" value="${esc(current.city)}"></label><label>Étage<input data-field="floor" value="${esc(current.floor)}"></label><label>Nature<select data-field="nature">${["Appartement","Maison","Studio","Local professionnel","Garage / parking"].map(x=>`<option ${x===current.nature?'selected':''}>${x}</option>`).join('')}</select></label><label>Location meublée<select data-field="furnished"><option ${current.furnished==='Non'?'selected':''}>Non</option><option ${current.furnished==='Oui'?'selected':''}>Oui</option></select></label></div></div>`;
    if(i===1)return `<div class="card"><div class="card-title"><div><h2>Les parties</h2><p>Coordonnées reprises dans le document final.</p></div></div><div class="grid"><label class="required">Bailleur / mandataire<input data-field="landlord" value="${esc(current.landlord)}"></label><label>Agent ayant réalisé le constat<input data-field="agent" value="${esc(current.agent)}"></label><label style="grid-column:1/-1">Adresse du bailleur / mandataire<input data-field="landlordAddress" value="${esc(current.landlordAddress)}"></label><label class="required">Locataire principal<input data-field="tenant" value="${esc(current.tenant)}"></label><label>Second locataire<input data-field="tenant2" value="${esc(current.tenant2)}"></label><label>Téléphone<input type="tel" data-field="phone" value="${esc(current.phone)}"></label><label>Email<input type="email" data-field="email" value="${esc(current.email)}"></label></div></div>`;
    if(i===2)return `<div class="card"><div class="card-title"><div><h2>Compteurs</h2><p>Photographiez aussi les index dans la pièce concernée.</p></div></div><div class="grid three">${meter("electricity","Électricité","kWh")}${meter("gas","Gaz","m³")}${meter("coldWater","Eau froide","m³")}${meter("hotWater","Eau chaude","m³")}<label>PRM / compteur électrique<input data-meter="electricityId" value="${esc(current.meters.electricityId)}"></label><label>N° compteur gaz<input data-meter="gasId" value="${esc(current.meters.gasId)}"></label></div></div><div class="card"><div class="card-title"><div><h2>Clés et moyens d’accès</h2><p>Quantité remise ou restituée.</p></div><button id="addKey" class="btn secondary small">＋ Ajouter</button></div><div id="keyList">${current.keys.map(k=>`<div class="keys-table"><label>Désignation<input data-key-name="${k.id}" value="${esc(k.name)}"></label><label>Quantité<input type="number" min="0" data-key-count="${k.id}" value="${esc(k.count)}"></label><button class="icon-btn" data-key-delete="${k.id}">×</button></div>`).join('')}</div></div>`;
    if(i===3)return `<div class="card"><div class="card-title"><div><h2>Inspection des pièces</h2><p>${current.type==='Sortie'?'La colonne « Entrée » rappelle l’état antérieur.':'Décrivez les défauts de façon factuelle et localisée.'}</p></div><button id="addRoom" class="btn">＋ Ajouter une pièce</button></div><div class="section-note">Astuce terrain : utilisez « Tout bon état », puis ne modifiez que les anomalies. Une pièce ne peut être validée si un élément reste « Non vérifié ».</div><div class="room-list">${current.rooms.map((r,idx)=>roomHTML(r,idx)).join('')}</div></div>`;
    if(i===4)return `<div class="card"><div class="card-title"><div><h2>Observations et réserves</h2><p>Conservez un vocabulaire objectif : emplacement, taille, couleur, fonctionnement.</p></div></div><div class="grid three"><label>Détecteur de fumée<select data-field="smokeDetector">${conditionsShort(current.smokeDetector)}</select></label><label>Propreté générale<select data-field="cleanliness">${conditionsShort(current.cleanliness)}</select></label><label>Chauffage / eau chaude<select data-field="heating">${conditionsShort(current.heating)}</select></label></div><div class="grid" style="margin-top:14px"><label>Observations générales<textarea data-field="observations" placeholder="Ex. Logement nettoyé, accès dégagé…">${esc(current.observations)}</textarea></label><label>Réserves / actions à suivre<textarea data-field="reserves" placeholder="Ex. Remplacement du joint à prévoir…">${esc(current.reserves)}</textarea></label></div></div>`;
    const issues=reviewIssues();return `<div class="review-grid"><div><div class="card"><div class="card-title"><div><h2>Signatures contradictoires</h2><p>Relisez le constat avec les parties avant signature.</p></div></div><div class="legal">Le présent état des lieux est établi contradictoirement entre les parties. Les signatures attestent la présence des signataires et leur prise de connaissance du contenu affiché. Chaque partie doit conserver un exemplaire du document. Les données et photographies restent enregistrées localement sur cet appareil jusqu’à leur suppression ou export.</div><label class="checkline"><input type="checkbox" data-field="accepted" ${current.accepted?'checked':''}>Les parties déclarent avoir relu le constat et acceptent de signer le document.</label><div class="signature-grid" style="margin-top:14px"><div class="signature-box"><label>Locataire<input data-field="signTenantName" value="${esc(current.signTenantName||current.tenant)}"></label><canvas id="signTenant"></canvas><button class="btn secondary small" data-clear-sign="signTenant">Effacer</button></div><div class="signature-box"><label>Bailleur / mandataire<input data-field="signLandlordName" value="${esc(current.signLandlordName||current.agent||current.landlord)}"></label><canvas id="signLandlord"></canvas><button class="btn secondary small" data-clear-sign="signLandlord">Effacer</button></div></div></div></div><div class="card"><div class="card-title"><div><h2>Contrôle final</h2><p>${issues.length?issues.length+' point(s) à vérifier':'Le dossier est prêt.'}</p></div></div><div class="checklist">${["Dossier identifié","Parties renseignées","Relevés et clés","Toutes les pièces validées","Observations","Signatures et accord"].map((x,j)=>`<div class="check ${stepComplete(j)?'ok':''}">${x}</div>`).join('')}</div>${issues.length?`<div class="section-note" style="margin-top:14px">${issues.map(esc).join('<br>')}</div>`:''}</div></div>`}
  function meter(k,label,unit){return `<div class="meter-card"><strong>${label}</strong><label class="unit">Index<input inputmode="decimal" data-meter="${k}" value="${esc(current.meters[k])}"><span>${unit}</span></label></div>`}
  function conditionsShort(v){return ["Non vérifié","Conforme","Fonctionnel","Non conforme","Non concerné"].map(x=>`<option ${x===v?'selected':''}>${x}</option>`).join('')}
  function roomHTML(r,idx){const remaining=r.elements.filter(e=>e.condition==="Non vérifié").length;return `<article class="room ${r.validated?'validated':''}"><div class="room-head"><div class="room-number">${idx+1}</div><div class="room-name">${esc(r.name)}</div><div class="room-summary">${r.validated?'✓ Validée':remaining+' non vérifié(s)'} · ${r.photos.length} photo(s)</div><button class="icon-btn no-print" data-room-toggle="${r.id}">⌄</button></div><div class="room-body" data-room-body="${r.id}" ${r.collapsed?'style="display:none"':''}><div class="quick-bar"><button class="btn secondary small" data-all-good="${r.id}">✓ Tout bon état</button><button class="btn ghost small" data-add-element="${r.id}">＋ Élément</button><button class="btn ghost small" data-copy-room="${r.id}">Copier</button><button class="btn danger small" data-delete-room="${r.id}">Supprimer</button></div><div class="element-head"><span>Élément</span><span>${current.type==='Sortie'?'État de sortie':'État'}</span><span>Description / anomalie</span></div>${r.elements.map(e=>`<div class="element"><input data-element-name="${r.id}:${e.id}" value="${esc(e.name)}"><select class="${e.condition.includes('Bon')||e.condition==='Neuf'?'state-good':e.condition.includes('Mauvais')||e.condition==='À remplacer'?'state-bad':''}" data-element-condition="${r.id}:${e.id}">${CONDITIONS.map(c=>`<option ${c===e.condition?'selected':''}>${c}${current.type==='Sortie'&&c===e.entryCondition?' · entrée':''}</option>`).join('')}</select><input data-k="description" data-element-description="${r.id}:${e.id}" value="${esc(e.description)}" placeholder="Ex. 2 rayures de 5 cm en bas à gauche"><button class="icon-btn" data-delete-element="${r.id}:${e.id}">×</button></div>`).join('')}<div class="photos">${r.photos.map((p,i)=>`<div class="photo"><img src="${p.data}" alt="Photo"><button data-delete-photo="${r.id}:${i}">×</button><input data-photo-caption="${r.id}:${i}" value="${esc(p.caption)}" placeholder="Légende / emplacement"></div>`).join('')}<label class="upload">＋ Ajouter des photos<input type="file" accept="image/*" capture="environment" multiple data-photo="${r.id}"></label></div><div style="display:flex;justify-content:flex-end;margin-top:13px"><button class="btn ${r.validated?'success':''}" data-validate-room="${r.id}">${r.validated?'✓ Pièce validée':'Valider la pièce'}</button></div></div></article>`}
  function bindEditor(){$$('[data-step]').forEach(b=>b.onclick=()=>{step=+b.dataset.step;renderEditor()});$$('[data-field]').forEach(x=>{const ev=x.type==='checkbox'?'change':'input';x.addEventListener(ev,()=>{current[x.dataset.field]=x.type==='checkbox'?x.checked:x.value;if(x.dataset.field==='type')renderEditor();else{schedule();$("#editorSub").textContent=`${current.reference} · ${current.address||'Nouvelle adresse'} · ${completion(current)} %`}})});$$('[data-meter]').forEach(x=>x.oninput=()=>{current.meters[x.dataset.meter]=x.value;schedule()});$("#addKey")?.addEventListener('click',()=>{current.keys.push({id:uid(),name:"Nouveau moyen d’accès",count:1});renderEditor();schedule()});$$('[data-key-name]').forEach(x=>x.oninput=()=>{current.keys.find(k=>k.id===x.dataset.keyName).name=x.value;schedule()});$$('[data-key-count]').forEach(x=>x.oninput=()=>{current.keys.find(k=>k.id===x.dataset.keyCount).count=x.value;schedule()});$$('[data-key-delete]').forEach(b=>b.onclick=()=>{current.keys=current.keys.filter(k=>k.id!==b.dataset.keyDelete);renderEditor();schedule()});$("#addRoom")?.addEventListener('click',openRoomModal);bindRooms();if(step===5){setupCanvas("signTenant","signTenant");setupCanvas("signLandlord","signLandlord")}}
  function bindRooms(){$$('[data-room-toggle]').forEach(b=>b.onclick=()=>{const r=findRoom(b.dataset.roomToggle);r.collapsed=!r.collapsed;renderEditor()});$$('[data-all-good]').forEach(b=>b.onclick=()=>{const r=findRoom(b.dataset.allGood);r.elements.forEach(e=>{if(e.condition==='Non vérifié')e.condition='Bon état'});renderEditor();schedule()});$$('[data-add-element]').forEach(b=>b.onclick=()=>{findRoom(b.dataset.addElement).elements.push({id:uid(),name:"Nouvel élément",condition:"Non vérifié",entryCondition:"Non vérifié",description:""});renderEditor();schedule()});$$('[data-copy-room]').forEach(b=>b.onclick=()=>{const src=findRoom(b.dataset.copyRoom),r=structuredClone(src);r.id=uid();r.name=uniqueRoomName(src.name);r.validated=false;r.photos=[];r.elements.forEach(e=>e.id=uid());current.rooms.splice(current.rooms.indexOf(src)+1,0,r);renderEditor();schedule()});$$('[data-delete-room]').forEach(b=>b.onclick=()=>askConfirm("Supprimer cette pièce ?","Ses éléments et ses photos seront supprimés.",()=>{current.rooms=current.rooms.filter(r=>r.id!==b.dataset.deleteRoom);renderEditor();schedule()}));$$('[data-element-name],[data-element-description]').forEach(x=>x.oninput=()=>{const [rid,eid]=(x.dataset.elementName||x.dataset.elementDescription).split(':'),e=findRoom(rid).elements.find(e=>e.id===eid);e[x.dataset.elementName?'name':'description']=x.value;findRoom(rid).validated=false;schedule()});$$('[data-element-condition]').forEach(x=>x.onchange=()=>{const [rid,eid]=x.dataset.elementCondition.split(':'),e=findRoom(rid).elements.find(e=>e.id===eid);e.condition=x.value;findRoom(rid).validated=false;renderEditor();schedule()});$$('[data-delete-element]').forEach(b=>b.onclick=()=>{const [rid,eid]=b.dataset.deleteElement.split(':'),r=findRoom(rid);r.elements=r.elements.filter(e=>e.id!==eid);r.validated=false;renderEditor();schedule()});$$('[data-validate-room]').forEach(b=>b.onclick=()=>{const r=findRoom(b.dataset.validateRoom),n=r.elements.filter(e=>e.condition==='Non vérifié').length;if(n){toast(`${n} élément(s) restent à vérifier`);return}r.validated=!r.validated;renderEditor();schedule()});$$('[data-photo]').forEach(x=>x.onchange=async()=>{const r=findRoom(x.dataset.photo);for(const f of x.files){if(!f.type.startsWith('image/'))continue;r.photos.push({data:await compressImage(f),caption:""})}renderEditor();schedule()});$$('[data-delete-photo]').forEach(b=>b.onclick=()=>{const [rid,i]=b.dataset.deletePhoto.split(':');findRoom(rid).photos.splice(+i,1);renderEditor();schedule()});$$('[data-photo-caption]').forEach(x=>x.oninput=()=>{const [rid,i]=x.dataset.photoCaption.split(':');findRoom(rid).photos[+i].caption=x.value;schedule()})}
  function findRoom(id){return current.rooms.find(r=>r.id===id)}function uniqueRoomName(base){let n=2,name=base;while(current.rooms.some(r=>r.name.toLowerCase()===name.toLowerCase()))name=`${base} ${n++}`;return name}
  async function compressImage(file){return new Promise((res,rej)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const scale=Math.min(1,1600/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);res(c.toDataURL('image/jpeg',.78))};img.onerror=rej;img.src=url})}
  function setupCanvas(id,field){const c=$("#"+id),ctx=c.getContext('2d'),d=devicePixelRatio||1,rect=c.getBoundingClientRect();c.width=rect.width*d;c.height=170*d;ctx.scale(d,d);ctx.lineWidth=2.2;ctx.lineCap='round';ctx.strokeStyle='#172033';if(current[field]){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,rect.width,170);img.src=current[field]}let down=false;const p=e=>{const r=c.getBoundingClientRect(),t=e.touches?.[0]||e;return{x:t.clientX-r.left,y:t.clientY-r.top}};const start=e=>{down=true;const q=p(e);ctx.beginPath();ctx.moveTo(q.x,q.y);e.preventDefault()};const move=e=>{if(!down)return;const q=p(e);ctx.lineTo(q.x,q.y);ctx.stroke();e.preventDefault()};const end=()=>{if(!down)return;down=false;current[field]=c.toDataURL('image/png');schedule()};c.onmousedown=start;c.onmousemove=move;window.addEventListener('mouseup',end);c.ontouchstart=start;c.ontouchmove=move;c.ontouchend=end;document.querySelector(`[data-clear-sign="${id}"]`).onclick=()=>{ctx.clearRect(0,0,c.width,c.height);current[field]="";schedule()}}
  function reviewIssues(){const x=[];if(!current.address||!current.city)x.push("Adresse complète à renseigner.");if(!current.landlord||!current.tenant)x.push("Bailleur et locataire à renseigner.");if(!Object.values(current.meters).some(Boolean))x.push("Aucun index de compteur renseigné.");if(!current.rooms.length)x.push("Aucune pièce ajoutée.");else if(current.rooms.some(r=>!r.validated))x.push("Toutes les pièces doivent être validées.");if(!current.accepted)x.push("L’accord de relecture doit être coché.");if(!current.signTenant||!current.signLandlord)x.push("Les deux signatures sont requises.");return x}
  function openRoomModal(){$("#roomPicker").innerHTML=Object.entries(ROOMS).map(([n,e])=>`<button class="room-option" data-room-option="${esc(n)}"><strong>${esc(n)}</strong><small>${e.length} éléments préconfigurés</small></button>`).join('');$("#roomModal").classList.add('open');$$('[data-room-option]').forEach(b=>b.onclick=()=>{current.rooms.push(makeRoom(b.dataset.roomOption));closeModal("roomModal");renderEditor();schedule()})}
  function closeModal(id){$("#"+id).classList.remove('open')}function askConfirm(title,text,fn){$("#confirmTitle").textContent=title;$("#confirmText").textContent=text;confirmAction=fn;$("#confirmModal").classList.add('open')}
  function finalise(){const issues=reviewIssues();if(issues.length){toast(`${issues.length} point(s) restent à vérifier`);step=5;renderEditor();return}current.status="Terminé";upsert();buildPrint();window.print()}
  function buildPrint(){const r=current,roomPages=r.rooms.map((room,idx)=>`<div class="print-section"><h2>${idx+1}. ${esc(room.name)}</h2><table class="print-table"><thead><tr><th>Élément</th>${r.type==='Sortie'?'<th>Entrée</th>':''}<th>État ${r.type.toLowerCase()}</th><th>Description</th></tr></thead><tbody>${room.elements.map(e=>`<tr><td>${esc(e.name)}</td>${r.type==='Sortie'?`<td>${esc(e.entryCondition)}</td>`:''}<td>${esc(e.condition)}</td><td>${esc(e.description||'—')}</td></tr>`).join('')}</tbody></table>${room.photos.length?`<div class="print-photos" style="margin-top:3mm">${room.photos.map(p=>`<div><img src="${p.data}"><div>${esc(p.caption)}</div></div>`).join('')}</div>`:''}</div>`).join('');$("#printView").innerHTML=`<article class="print-page"><div class="print-brand"><img src="./icon-192.png"><div><h1>État des lieux d’${esc(r.type.toLowerCase())}</h1><p>${esc(r.reference)} · ${new Date(r.date).toLocaleString('fr-FR')}</p></div></div><div class="print-section"><h2>Bien concerné</h2><table class="print-table"><tr><th>Adresse</th><td>${esc(r.address)}, ${esc(r.postalCode)} ${esc(r.city)}</td></tr><tr><th>Bien</th><td>${esc(r.nature)} · ${esc(r.lot)} · étage ${esc(r.floor||'—')} · meublé : ${esc(r.furnished)}</td></tr></table></div><div class="print-section"><h2>Parties</h2><table class="print-table"><tr><th>Bailleur / mandataire</th><td>${esc(r.landlord)}</td><th>Locataire(s)</th><td>${esc([r.tenant,r.tenant2].filter(Boolean).join(' / '))}</td></tr><tr><th>Agent</th><td>${esc(r.agent||'—')}</td><th>Coordonnées</th><td>${esc([r.phone,r.email].filter(Boolean).join(' · ')||'—')}</td></tr></table></div><div class="print-section"><h2>Compteurs et accès</h2><table class="print-table"><tr>${Object.entries(r.meters).map(([k,v])=>`<th>${esc(k)}</th><td>${esc(v||'—')}</td>`).join('')}</tr></table><table class="print-table" style="margin-top:2mm">${r.keys.map(k=>`<tr><td>${esc(k.name)}</td><td>${esc(k.count)}</td></tr>`).join('')}</table></div>${roomPages}<div class="print-section"><h2>Observations et réserves</h2><p><strong>Observations :</strong> ${esc(r.observations||'Aucune')}</p><p><strong>Réserves :</strong> ${esc(r.reserves||'Aucune')}</p></div><div class="print-section"><h2>Signatures</h2><p>Document établi contradictoirement. Les parties reconnaissent avoir relu le présent constat et en avoir reçu un exemplaire.</p><div class="print-signs"><div class="print-sign"><strong>Locataire — ${esc(r.signTenantName||r.tenant)}</strong><img src="${r.signTenant}"></div><div class="print-sign"><strong>Bailleur / mandataire — ${esc(r.signLandlordName||r.landlord)}</strong><img src="${r.signLandlord}"></div></div></div><div class="page-footer">${esc(r.reference)} · Document généré avec Constat · ${new Date().toLocaleString('fr-FR')}</div></article>`}
  function exportBackup(){const blob=new Blob([JSON.stringify({app:"Constat",version:1,exportedAt:new Date().toISOString(),records},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`constat-sauvegarde-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast("Sauvegarde téléchargée")}
  async function importBackup(file){try{const data=JSON.parse(await file.text()),rows=Array.isArray(data)?data:data.records;if(!Array.isArray(rows))throw 0;askConfirm("Importer la sauvegarde ?",`${rows.length} dossier(s) seront ajoutés ou mis à jour.`,()=>{for(const r of rows){const i=records.findIndex(x=>x.id===r.id);if(i<0)records.push(r);else records[i]=r}persist();renderHome();toast("Sauvegarde importée")})}catch{toast("Fichier de sauvegarde invalide")}}
  $("#newEntry").onclick=()=>newRecord("Entrée");$("#newExit").onclick=()=>newRecord("Sortie");$("#backBtn").onclick=()=>{upsert();showView("homeView");renderHome()};$("#duplicateBtn").onclick=()=>duplicate(current.id,true);$("#search").oninput=renderHome;$("#statusFilter").onchange=renderHome;$("#prevBtn").onclick=()=>{if(step>0){step--;renderEditor()}};$("#nextBtn").onclick=()=>{if(step<5){step++;renderEditor()}else finalise()};$("#printBtn").onclick=()=>{buildPrint();window.print()};$("#backupBtn").onclick=exportBackup;$("#importFile").onchange=e=>e.target.files[0]&&importBackup(e.target.files[0]);$("#addCustomRoom").onclick=()=>{const n=$("#customRoom").value.trim();if(!n)return;const r=makeRoom("Autre");r.name=n;current.rooms.push(r);closeModal("roomModal");renderEditor();schedule()};$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$("#confirmYes").onclick=()=>{closeModal("confirmModal");confirmAction?.();confirmAction=null};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$("#installBtn").classList.remove('hidden')});$("#installBtn").onclick=async()=>{deferredInstall?.prompt();deferredInstall=null;$("#installBtn").classList.add('hidden')};window.addEventListener('beforeunload',()=>current&&upsert());load();renderHome();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js');
  /* Micro-interactions et garde-fous de confort */
  const persistDirect=persist;
  persist=function(){
    try{persistDirect()}
    catch(error){
      setSave("Stockage saturé",true);
      toast("Stockage presque plein : exportez une sauvegarde et réduisez les photos.");
    }
  };
  document.addEventListener("pointerdown",event=>{
    const target=event.target.closest("button,.room-option");
    if(!target||target.disabled||matchMedia("(prefers-reduced-motion: reduce)").matches)return;
    const dot=document.createElement("span");dot.className="ripple";dot.style.left=event.clientX+"px";dot.style.top=event.clientY+"px";document.body.appendChild(dot);setTimeout(()=>dot.remove(),520);
  });
  document.addEventListener("click",event=>{
    if(event.target.closest("[data-validate-room],#nextBtn,#confirmYes")&&navigator.vibrate)navigator.vibrate(14);
  });
  document.addEventListener("keydown",event=>{
    if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="s"){
      event.preventDefault();current?upsert():exportBackup();toast(current?"Dossier enregistré":"Sauvegarde téléchargée");
    }
    if(event.key==="Escape")$$('.modal.open').forEach(modal=>closeModal(modal.id));
  });
  document.addEventListener("visibilitychange",()=>{if(document.hidden&&current)upsert()});
  document.addEventListener("change",event=>{
    const token=event.target.dataset?.elementCondition;
    if(!token||!current)return;
    const [roomId,elementId]=token.split(":");
    const element=findRoom(roomId)?.elements.find(item=>item.id===elementId);
    if(element)element.condition=String(element.condition).replace(" · entrée","");
  });
  </script>
<script src="./logic-v2.js"></script>
<script src="./mobile-v3.js"></script>
<script src="./workflow-v4.js"></script>
</body>
</html>
