"use strict";

const panelHTMLV3=panelHTML;
panelHTML=function(index){
  if(index!==1)return panelHTMLV3(index);
  return `<div class="card identity-card"><div class="card-title"><div><h2>Personnes présentes</h2><p>Ces informations seront reprises automatiquement dans les signatures et le document final.</p></div></div><div class="identity-group"><h3>Bailleur ou mandataire</h3><div class="grid"><label class="required">Nom ou raison sociale<input data-field="landlord" value="${esc(current.landlord)}" autocomplete="organization"></label><label>Agent réalisant le constat<input data-field="agent" value="${esc(current.agent)}" autocomplete="name"></label><label style="grid-column:1/-1">Adresse postale<input data-field="landlordAddress" value="${esc(current.landlordAddress)}" autocomplete="street-address"></label><label>Téléphone<input type="tel" data-field="landlordPhone" value="${esc(current.landlordPhone||'')}" autocomplete="tel"></label><label>Email<input type="email" data-field="landlordEmail" value="${esc(current.landlordEmail||'')}" autocomplete="email"></label></div></div><div class="identity-group"><h3>Locataire principal</h3><div class="grid"><label class="required">Nom complet<input data-field="tenant" value="${esc(current.tenant)}" autocomplete="name"></label><label>Date de naissance<input type="date" data-field="tenantBirth" value="${esc(current.tenantBirth||'')}"></label><label style="grid-column:1/-1">Nouvelle adresse ou adresse de correspondance<input data-field="tenantAddress" value="${esc(current.tenantAddress||'')}" autocomplete="street-address"></label><label>Téléphone<input type="tel" data-field="phone" value="${esc(current.phone)}" autocomplete="tel"></label><label>Email<input type="email" data-field="email" value="${esc(current.email)}" autocomplete="email"></label></div></div><div class="identity-group"><h3>Second locataire <span>facultatif</span></h3><div class="grid"><label>Nom complet<input data-field="tenant2" value="${esc(current.tenant2)}" autocomplete="name"></label><label>Téléphone<input type="tel" data-field="tenant2Phone" value="${esc(current.tenant2Phone||'')}"></label><label>Email<input type="email" data-field="tenant2Email" value="${esc(current.tenant2Email||'')}"></label></div></div></div>`;
};

const renderEditorV4=renderEditor;
renderEditor=function(){
  renderEditorV4();
  const status=document.querySelector(".mobile-step-status");
  if(status)status.innerHTML=`<div class="journey-copy"><span>${step+1}/${STEPS.length}</span><strong>${STEPS[step]}</strong></div><div class="journey-dots">${STEPS.map((label,index)=>`<i class="${index<step?'done':index===step?'current':''}" title="${label}"></i>`).join("")}</div>`;
};

function selectedRoomsForWizard(container){return[...container.querySelectorAll("[data-wizard-room].selected")].map(button=>button.dataset.wizardRoom)}
function expandBedroomSelection(names,count){const result=names.filter(name=>!/^Chambre \d+$/.test(name));if(!result.includes("Chambre"))return result;for(let index=2;index<=Math.max(1,count-1);index++)result.push(`Chambre ${index}`);return result}
function configuredRoom(name){if(!/^Chambre \d+$/.test(name))return makeRoom(name);const room=makeRoom("Chambre");room.name=name;return room}
function bedroomRooms(count){const result=[];for(let i=1;i<=count;i++)result.push(i===1?"Chambre":`Chambre ${i}`);return result}
function defaultRoomNames(nature,count){const names=["Entrée / dégagement","Séjour","Cuisine",nature==="Studio"?"Salle de bains":"Salle d’eau","WC",...bedroomRooms(nature==="Studio"?0:Math.max(0,count-1))];return [...new Set(names)]}

function startSetupWizard(type,seed={}){
  let wizard=document.querySelector("#setupWizard");if(!wizard){wizard=document.createElement("div");wizard.id="setupWizard";wizard.className="modal";document.body.appendChild(wizard)}
  let page=0;const state={type,address:seed.address||"",postalCode:seed.postalCode||"",city:seed.city||"",lot:seed.lot||"",nature:seed.nature||"Appartement",furnished:seed.furnished||"Non",count:seed.count||2,landlord:seed.landlord||"",agent:seed.agent||"",tenant:seed.tenant||"",phone:seed.phone||"",email:seed.email||"",rooms:seed.rooms?.map(room=>room.name)||[]};
  function draw(){
    const titles=["Le logement","Les pièces","Les personnes"];
    wizard.innerHTML=`<div class="modal-card setup-card"><div class="setup-top"><button class="icon-btn" data-setup-close>×</button><div><span>Préparation · ${page+1}/3</span><h2>${titles[page]}</h2></div></div><div class="setup-body">${page===0?`<p class="setup-question">Quel logement allez-vous inspecter ?</p><div class="grid"><label class="required" style="grid-column:1/-1">Adresse<input data-setup="address" value="${esc(state.address)}" placeholder="12 rue…" autofocus></label><label>Code postal<input data-setup="postalCode" value="${esc(state.postalCode)}" inputmode="numeric"></label><label>Ville<input data-setup="city" value="${esc(state.city)}"></label><label>Lot / appartement<input data-setup="lot" value="${esc(state.lot)}"></label><label>Type de bien<select data-setup="nature">${["Appartement","Maison","Studio","Local professionnel"].map(value=>`<option ${value===state.nature?'selected':''}>${value}</option>`).join('')}</select></label><label>Pièces principales<select data-setup="count">${[1,2,3,4,5,6,7,8].map(value=>`<option ${value==state.count?'selected':''}>${value}</option>`).join('')}</select></label><label>Location meublée<select data-setup="furnished"><option ${state.furnished==='Non'?'selected':''}>Non</option><option ${state.furnished==='Oui'?'selected':''}>Oui</option></select></label></div>`:page===1?`<p class="setup-question">Quelles pièces sont présentes ?</p><p class="muted setup-help">Les critères d’inspection seront adaptés automatiquement à chaque pièce.</p><div class="wizard-room-grid">${Object.keys(ROOMS).map(name=>`<button class="wizard-room ${state.rooms.includes(name)||(!state.rooms.length&&defaultRoomNames(state.nature,+state.count).includes(name))?'selected':''}" data-wizard-room="${esc(name)}"><span>${esc(name)}</span><small>${ROOMS[name].length} points</small></button>`).join('')}</div>`:`<p class="setup-question">Qui participera au constat ?</p><div class="grid"><label class="required">Bailleur / mandataire<input data-setup="landlord" value="${esc(state.landlord)}"></label><label>Agent présent<input data-setup="agent" value="${esc(state.agent)}"></label><label class="required">Locataire principal<input data-setup="tenant" value="${esc(state.tenant)}"></label><label>Téléphone<input type="tel" data-setup="phone" value="${esc(state.phone)}"></label><label style="grid-column:1/-1">Email<input type="email" data-setup="email" value="${esc(state.email)}"></label></div>`}</div><div class="setup-actions">${page?'<button class="btn secondary" data-setup-back>Retour</button>':'<span></span>'}<button class="btn" data-setup-next>${page===2?'Créer le dossier':'Continuer'}</button></div></div>`;
    wizard.classList.add("open");wizard.querySelector("[data-setup-close]").onclick=()=>wizard.classList.remove("open");wizard.querySelectorAll("[data-setup]").forEach(input=>input.oninput=()=>state[input.dataset.setup]=input.value);wizard.querySelectorAll("[data-wizard-room]").forEach(button=>button.onclick=()=>button.classList.toggle("selected"));wizard.querySelector("[data-setup-back]")?.addEventListener("click",()=>{page--;draw()});wizard.querySelector("[data-setup-next]").onclick=()=>{
      if(page===0&&(!state.address.trim()||!state.city.trim())){toast("Renseignez au moins l’adresse et la ville");return}
      if(page===1){state.rooms=expandBedroomSelection(selectedRoomsForWizard(wizard),+state.count);if(!state.rooms.length){toast("Sélectionnez au moins une pièce");return}}
      if(page<2){page++;draw();return}
      if(!state.landlord.trim()||!state.tenant.trim()){toast("Renseignez le bailleur et le locataire");return}
      const record=emptyRecord(type);Object.assign(record,state);record.rooms=(seed.rooms?.length?seed.rooms:state.rooms.map(configuredRoom));record.signTenantName=record.tenant;record.signLandlordName=record.agent||record.landlord;if(seed.referencePdf)record.referencePdf=seed.referencePdf;if(seed.sourceReference)record.sourceReference=seed.sourceReference;records.push(record);current=record;step=0;persist();wizard.classList.remove("open");renderEditor();showView("editorView");
    };
  }
  draw();
}

async function readImportedPdf(file){
  toast("Lecture du PDF en cours…");
  const pdfjs=await import("./vendor/pdf.min.mjs");pdfjs.GlobalWorkerOptions.workerSrc="./vendor/pdf.worker.min.mjs";
  const documentPdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let text="";
  for(let pageNumber=1;pageNumber<=documentPdf.numPages;pageNumber++){const page=await documentPdf.getPage(pageNumber),content=await page.getTextContent();text+="\n"+content.items.map(item=>item.str).join(" ")}
  const cleaned=text.replace(/\s+/g," ").trim(),flat=normalize(cleaned);const pick=(regex)=>cleaned.match(regex)?.[1]?.trim()||"";
  const postal=cleaned.match(/\b(\d{5})\s+([A-ZÀ-Ÿ][A-Za-zÀ-ÿ' -]{2,})/);const seed={referencePdf:{name:file.name,size:file.size,importedAt:new Date().toISOString()},address:pick(/(?:Adresse(?: du logement)?|Bien situé)[\s:]+(.{5,100}?)(?=\s(?:Lot|Code postal|Bailleur|Locataire|$))/i),postalCode:postal?.[1]||"",city:postal?.[2]?.trim()||"",tenant:pick(/Locataire(?: principal)?[\s:]+([A-ZÀ-Ÿ][A-Za-zÀ-ÿ' -]{2,60})/i),landlord:pick(/(?:Bailleur|Mandataire)[\s:]+(.{2,70}?)(?=\s(?:Adresse|Locataire|Représenté|$))/i),furnished:/meubl[eé]\s*[:]?\s*oui/i.test(cleaned)?"Oui":"Non",nature:/\bstudio\b/i.test(cleaned)?"Studio":/\bmaison\b/i.test(cleaned)?"Maison":"Appartement",sourceReference:pick(/(?:Référence|N° dossier)[\s:]+([A-Z0-9-]+)/i)};
  const detected=Object.keys(ROOMS).filter(name=>flat.includes(normalize(name).split(" /")[0]));seed.rooms=detected.map(name=>{const room=makeRoom(name);room.elements.forEach(element=>{const label=normalize(element.name),position=flat.indexOf(label);if(position>=0){const area=cleaned.slice(position,position+180),condition=CONDITIONS.find(value=>normalize(area).includes(normalize(value)));element.entryCondition=condition||"Non documenté";element.entryDescription=area.slice(label.length,150).trim()}else element.entryCondition="Non documenté";element.condition="Non vérifié"});return room});
  toast(`${documentPdf.numPages} page(s) analysée(s)`);return seed;
}

showExitChooser=function(){
  const entries=records.filter(record=>record.type==="Entrée"&&record.rooms?.length).sort((a,b)=>b.date.localeCompare(a.date));let modal=document.querySelector("#exitChooser");if(!modal){modal=document.createElement("div");modal.id="exitChooser";modal.className="modal";document.body.appendChild(modal)}
  modal.innerHTML=`<div class="modal-card source-modal"><div class="modal-head"><div><span class="source-kicker">État des lieux de sortie</span><h2>Choisir la référence d’entrée</h2><p class="muted">L’original restera intact.</p></div><button class="icon-btn" data-exit-close>×</button></div><div class="source-list">${entries.map(entry=>`<button class="source-card" data-source-entry="${entry.id}"><strong>${esc(entry.address||"Adresse non renseignée")}</strong><span>${esc(entry.reference)} · ${new Date(entry.date).toLocaleDateString("fr-FR")} · ${esc(entry.tenant||"Sans locataire")}</span></button>`).join('')}</div><label class="pdf-import"><input type="file" accept="application/pdf" data-import-pdf><strong>Importer un ancien PDF</strong><span>Le logement, les parties, les pièces et les états détectés seront préremplis.</span></label><button class="btn ghost" data-blank-exit style="width:100%;margin-top:9px">Continuer sans état des lieux d’entrée</button></div>`;
  modal.classList.add("open");modal.querySelector("[data-exit-close]").onclick=()=>modal.classList.remove("open");modal.querySelectorAll("[data-source-entry]").forEach(button=>button.onclick=()=>{modal.classList.remove("open");duplicate(button.dataset.sourceEntry,true)});modal.querySelector("[data-blank-exit]").onclick=()=>{modal.classList.remove("open");startSetupWizard("Sortie")};modal.querySelector("[data-import-pdf]").onchange=async event=>{const file=event.target.files[0];if(!file)return;try{const seed=await readImportedPdf(file);modal.classList.remove("open");startSetupWizard("Sortie",seed)}catch(error){console.error(error);toast("Ce PDF n’a pas pu être analysé")}};
};

document.querySelector("#newEntry").onclick=()=>startSetupWizard("Entrée");
document.querySelector("#newExit").onclick=showExitChooser;
document.addEventListener("input",event=>{if(!current)return;const field=event.target.dataset?.field;if(field==="tenant")current.signTenantName=current.tenant;if(field==="agent"||field==="landlord")current.signLandlordName=current.agent||current.landlord});
